name: Wiki
on: [gollum]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update Wiki
      run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${{ secrets.NETLIFY }}"
